//
//  ProductDetailWorkerTests.swift
//  AdiChallenge
//
//  Created by Tolga Taş on 25.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import AdiChallenge
import XCTest

class ProductDetailWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ProductDetailWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupProductDetailWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupProductDetailWorker()
  {
    sut = ProductDetailWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
    func testProductDetailService() {
    let expectation = self.expectation(description: "Wait for productDetailService() to return.")
        let productId: String = "HI333"
        sut.productDetailService(productId: productId) { (product, error) in
            XCTAssert(error == nil, "Api Call Failed")
            expectation.fulfill()
        }
    waitForExpectations(timeout: 60)
  }
}
