//
//  ProductListPresenter.swift
//  AdiChallenge
//
//  Created by Tolga Taş on 25.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListPresentationLogic {
    func presentFetchedProducts(response: ProductList.Response)
}

class ProductListPresenter: ProductListPresentationLogic {
    weak var viewController: ProductListDisplayLogic?
  
    // MARK: - Present Fetched Products
  
    func presentFetchedProducts(response: ProductList.Response) {
        guard let products = response.productModel else {
            guard let error = response.error else { return }
            viewController?.displayError(error: error)
            return
        }
        let productListViewModel = ProductListViewModel(resultModel: products)
        let viewModel = ProductList.ViewModel(displayResults: productListViewModel)
        viewController?.displayProductList(viewModel: viewModel)
    }
}
