//
//  ProductListWorker.swift
//  AdiChallenge
//
//  Created by Tolga Taş on 25.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductListWorker {
    func productListService(completion: @escaping(([ProductModel]?, APIError?) -> Void)) {
        ProductsService.shared.productServiceCall { (product, error) in
            completion(product, error)
        }
    }
}
