//
//  ProductListModels.swift
//  AdiChallenge
//
//  Created by Tolga Taş on 25.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductList {
    // MARK: Use cases
  
        struct Request {}
        struct Response {
            var productModel: [ProductModel]?
            var error: APIError?
        }
        struct ViewModel {
            var displayResults: ProductListViewModel
        }
}
