//
//  ProductDetailWorker.swift
//  AdiChallenge
//
//  Created by Tolga Taş on 25.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductDetailWorker {
    func productDetailService(productId: String, completion: @escaping((ProductDetailModel?, APIError?) -> Void)) {
        ProductsService.shared.productDetailServiceCall(productId: productId) { (product, error) in
            completion(product, error)
        }
    }
    
    func submitReview(productId: String, rating: Int, review: String, completion: @escaping((ReviewModel?, APIError?) -> Void)) {
        let json: [String: Any] = ["id": "\(productId)",
                                   "locale": "en",
                                   "rating": rating,
                                   "text": "\(review)"]
        ReviewServices.shared.submitReview(productId: productId, reviewModel: json) { (result, error) in
            completion(result, error)
        }
    }
}
